runtime: nodejs24
service: default

automatic_scaling:
  min_instances: 0
  max_instances: 5

env_variables:
  TZ: "Asia/Tokyo"
  LW_USE_MOCK: "false"
  DEFAULT_RESULT_LIMIT: "5"
  MIN_LEAD_MINUTES: "30"

  LW_API_BASE_URL: "https://www.worksapis.com/v1.0"
  LW_AUTH_TOKEN_URL: "https://auth.worksmobile.com/oauth2/v2.0/token"
  LW_OAUTH_REDIRECT_URI: "https://line-works-schedule.an.r.appspot.com/api/v1/auth/callback"
  LW_OAUTH_SCOPES: "calendar calendar.read directory directory.read"

  LW_CALENDAR_BUSY_PATH_TEMPLATE: "/users/{userId}/calendar/events?fromDateTime={from}&untilDateTime={to}"
  LW_CALENDAR_CREATE_PATH_TEMPLATE: "/users/{calendarId}/calendar/events"

  LW_CLIENT_ID: "JGXXyOcOgZChPcmr7Yse"
  LW_CLIENT_SECRET: "sYGJ7fmbLj"
  LW_SERVICE_ACCOUNT: "ns97l.serviceaccount@hrdcorporation"
  LW_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6YPvV9kwKw/HC\nJbR3IlI6kKaSiX+wj2/wolMDYd8sWYCVBuLdwDJVoCMaAFLYWRUyBBy+C23Ut5Mw\nlfJrtzTHDgP+7pDoDNQMSxOPMsUmw6yOfze2XSuO7fgcUqL5w4r2tNcuBFkevM/+\n10PFyUkPvY04kKqqwPwIIVd4J5mekn+0wPL+LPnX23nkd3gquciFlhRqIfJGOAB+\ndcAz94ep7wCPBoBnvbEyp1uDJafj0pAJEhY7aoUOA3Y+HxJmZmLptumUk2O8+1I3\nP2geM5kH7luQImVvp6IwI4KIa3W6WgCaHu3q8g1EKqElSUVNppH4q+sxpACHDX/O\nanMvBVFpAgMBAAECggEAGwbYThEeusrqQmSUVFhKQ0rZlNNSjGhoa6UmU428PqKl\n9jZe7Jgj1G3Z2TnlyZC1daDKCDcBEMEkG34K/tq80QazxqKSqcu+bh/u8KuEklf6\nrFk/W3cMS3gvq+/ByWU1QAw+TeJ8h+wKX2KY5dQH/7vVgDfeP8+nXIh1NivL54YH\n2CHr7QLixDh1UBjaaEboIWaFWx897pFPqvrDC3Zsx7ACR6EEFmZYSeSxc6yFYIS8\ncBsy/k5vwvKPl1feCedRvdArufaRAOHDtBrPOwcwaCd3uJ6f+avPY3qArcbx85Iu\nv5MGoIxqPvd82vviUFJKP1RR1vS/nV4ZcYlfdbTR3wKBgQD/H2tpHINiNzCJ7fct\ncO5pmZRj7vD1okg0Smvgr6MsXDvjgxVQm6bCamihcb/WPlSYtQZuPe0QcaRuQtUE\n87ocZgth22QxoIQF4n9AVenOY7pABbd6KD1HAhwDz3Trt2eyybQJEas6vu9qUiGh\nr/WuIkdfORiteZYswQw2C4uOswKBgQC7BQzOUWCLPzqbeNxFCdgTBHLAnOajWQ66\nnmcoJc6NRPpFBKJVwR1I73doShoOVeAZtGkZej0/j4be4K0azTapo/veuktcGDdV\nOVPzvl0swHbcpyMZ7Tigx0QPQuSUQsH4Nqa3cZRvRcmOcIs7eGSunoy0uETlApBr\n9zeOhyZtcwKBgFCA0Zvxa2Pqll5vwLeOEy0vUSvXkiFwe+hEM5ZK1eqBkERScL9m\n3lAq06leA3LPaFJnjQfsconl0kUYwa82WVvst1rBp/Qg+ogA2LasZYLC5Vqecy8Q\n04U8nSp2pCZdUVORYkYaVTXMWi/qisJCi/vOxUa+9ZKH82Nb50aGjhsRAoGBAKOl\nPZljN7lgsGXOkd+PR5UMdWT5Zg9VJEBDzzwgKOcQjnXKIkorWvaxI6kL/lTA7AFS\nDg0PG3z8mCV6L76eBtDV/tTb6olBX1mhekZ0Mo+wMdHOJjbPjpeRBYrdG6pn59bL\n64HlTt83D7El5Y86P89USQbxnsdNQRZYEjMTK5rlAoGBAInTJngOfVG+iWgR5mO9\nFidKzXxa9s2y58xLvma0J17O9nYI7fn3c6RP22xTLER3Z+Zmcgpjkr3K4HXTxuLf\nVAnFlhi0zp3kuhdLLMXczTOFKIXS4muzrSz1xyGGEHWYj+bMxEuZWwguTu1AhHJG\niqMtzn06DH2saLwsHBJocpt+\n-----END PRIVATE KEY-----"